# Configuração Netlify para o app Gerência Financeira CETEM (v0.5)
[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
